"use strict";
const bcrypt = require("bcryptjs");

module.exports = {
  up: async (queryInterface, Sequelize) => {
    // const hashedPassword = await bcrypt.hash("1234", 10);
    return queryInterface.bulkInsert("users", [
      {
        id: 1,
        first_name: "Tracy",
        last_name: "Kemp",
        email: "tracy@gmail.com",
        password: await bcrypt.hash("1234", 10),
        facebook_id: "2020",
        google_id: "2020",
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 2,
        first_name: "Jay",
        last_name: "Kemp",
        email: "jay@gmail.com",
        password: await bcrypt.hash("1234", 10),
        facebook_id: "2024",
        google_id: "2022",
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 3,
        first_name: "Tan",
        last_name: "Jai",
        email: "tanjai@gmail.com",
        password: await bcrypt.hash("1234", 10),
        facebook_id: "2025",
        google_id: "2029",
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 4,
        first_name: "Kenta",
        last_name: "Kunjung",
        email: "kenta@gmail.com",
        password: await bcrypt.hash("1234", 10),
        facebook_id: "2021",
        google_id: "202",
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 5,
        first_name: "Bo",
        last_name: "jung",
        email: "Bojung@gmail.com",
        password: await bcrypt.hash("1234", 10),
        facebook_id: "114",
        google_id: "229",
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 6,
        first_name: "Abel",
        last_name: "Lord",
        email: "Abel@gmail.com",
        password: await bcrypt.hash("1234", 10),
        facebook_id: "115",
        google_id: "230",
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 7,
        first_name: "Alex",
        last_name: "jack",
        email: "alex@gmail.com",
        password: await bcrypt.hash("1234", 10),
        facebook_id: "116",
        google_id: "231",
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 8,
        first_name: "Adin",
        last_name: "Boss",
        email: "Adin@gmail.com",
        password: await bcrypt.hash("1234", 10),
        facebook_id: "117",
        google_id: "232",
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 9,
        first_name: "Ya",
        last_name: "jung",
        email: "Ya@gmail.com",
        password: await bcrypt.hash("1234", 10),
        facebook_id: "118",
        google_id: "233",
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 10,
        first_name: "Jay",
        last_name: "Lock",
        email: "jlock@gmail.com",
        password: await bcrypt.hash("1234", 10),
        facebook_id: "119",
        google_id: "234",
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 11,
        first_name: "Abdhul",
        last_name: "Aham",
        email: "abvraham@gmail.com",
        password: await bcrypt.hash("1234", 10),
        facebook_id: "120",
        google_id: "235",
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 12,
        first_name: "kelly",
        last_name: "jung",
        email: "kelljung@gmail.com",
        password: await bcrypt.hash("1234", 10),
        facebook_id: "121",
        google_id: "236",
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 13,
        first_name: "Momo",
        last_name: "jung",
        email: "moojung@gmail.com",
        password: await bcrypt.hash("1234", 10),
        facebook_id: "122",
        google_id: "237",
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 14,
        first_name: "call",
        last_name: "nyuung",
        email: "caruljung@gmail.com",
        password: await bcrypt.hash("1234", 10),
        facebook_id: "123",
        google_id: "238",
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 15,
        first_name: "Warit",
        last_name: "tamm",
        email: "waritjung@gmail.com",
        password: await bcrypt.hash("1234", 10),
        facebook_id: "124",
        google_id: "239",
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 16,
        first_name: "meek",
        last_name: "mill",
        email: "meek@gmail.com",
        password: await bcrypt.hash("1234", 10),
        facebook_id: "125",
        google_id: "240",
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 17,
        first_name: "Lo",
        last_name: "jung",
        email: "loojung@gmail.com",
        password: await bcrypt.hash("1234", 10),
        facebook_id: "126",
        google_id: "241",
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 18,
        first_name: "Rosd",
        last_name: "wood",
        email: "rose@gmail.com",
        password: await bcrypt.hash("1234", 10),
        facebook_id: "127",
        google_id: "242",
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 19,
        first_name: "Ahio",
        last_name: "bleed",
        email: "ahio@gmail.com",
        password: await bcrypt.hash("1234", 10),
        facebook_id: "128",
        google_id: "243",
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 20,
        first_name: "J",
        last_name: "Cole",
        email: "Cole@gmail.com",
        password: await bcrypt.hash("1234", 10),
        facebook_id: "129",
        google_id: "244",
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
    await queryInterface.bulkDelete("users", null, {});
  },
};
